DATASET:
  DATA_SCALE: [3]
  OUT_PATCH_SIZE: 144
LOG:
  SAVE: RCAN_x3
DATASET:
  DATA_EXT: bin
  DATA_DIR: ../rcan-it/
  DATA_TRAIN: ['MyData']
  DATA_VAL: ['MyData']
  DATA_TEST: ['MyData']
  DATA_RANGE: [[1, 450], [451, 500]]