DATASET:
  DATA_SCALE: [4]
  OUT_PATCH_SIZE: 192
LOG:
  SAVE: RCAN_x4
DATASET:
  DATA_EXT: bin
  DATA_DIR: ../rcan-it/
  DATA_TRAIN: ['MyData']
  DATA_VAL: ['MyData']
  DATA_TEST: ['MyData_Test']
  DATA_RANGE: [[1, 9410], [9411, 11002]]
